language: python
sudo: false
python:
  - "2.7"
install:
  - source cfg4dev
  - pip install coveralls
script:
  - python setup.py sdist --formats=gztar
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package yar
after_success:
  - coveralls || true
